language: go

go:
  #- 1.5.2
  #- 1.6.1
  - 1.7.x
  - 1.8.x
  - tip

addons:
  firefox: 53.0.3 #latest

env:
  global:
    - DISPLAY=:99.0
  matrix:
    - FIREFOX_VERSION=53.0.3
    - FIREFOX_VERSION=52.0
    - FIREFOX_VERSION=51.0
    - FIREFOX_VERSION=50.0

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
  - sh -e /etc/init.d/xvfb start

install:
  - export FIREFOX_SOURCE_URL="https://download.mozilla.org/?product=$FIREFOX_VERSION&lang=en-US&os=linux64"
  - wget -O /tmp/firefox.tar.bz2 $FIREFOX_SOURCE_URL
  - mkdir -p $HOME/ff
  - tar -jvxf /tmp/firefox.tar.bz2 -C $HOME/ff/

before_script:
  - ls $HOME/ff/
  - $HOME/ff/bin/firefox --version
  - $HOME/ff/bin/firefox -marionette > /dev/null 2>&1 &
  - sleep 5
  - ps aux | grep firefox

script:
  #- go test -test.v
  - go test -test.v -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - $HOME/gopath/bin/goveralls -service=travis-ci