language: go

go:
  - 1.5.2

addons:
  firefox: latest

env:
  global:
    - DISPLAY=:99.0

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
  - sh -e /etc/init.d/xvfb start

before_script:
  - firefox --version
  - firefox -marionette > /dev/null 2>&1 &
  - sleep 3
  - ps aux | grep firefox

script:
  - go test
  - $HOME/gopath/bin/goveralls -service=travis-ci