language: go
sudo: required

go:
  - 1.8.x
  - 1.9.x
  - 1.10.3
  - tip

#addons:
#  firefox: latest

env:
  global:
    - DISPLAY=:99.0
    - MOZ_HEADLESS=1
  matrix:
    - FIREFOX_VERSION=56.0
    - FIREFOX_VERSION=57.0.1
    - FIREFOX_VERSION=60.0
    - FIREFOX_VERSION=61.0.2
    - FIREFOX_VERSION=62.0
    - FIREFOX_VERSION=63.0

matrix:
  fast_finish: true
  allow_failures:
  #  env: FIREFOX_VERSION=56.0

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
  - sh -e /etc/init.d/xvfb start
  - sleep 3

install:
  - export FIREFOX_SOURCE_URL="https://download.mozilla.org/?product=firefox-$FIREFOX_VERSION&lang=en-US&os=linux64"
  - wget -O /tmp/firefox.tar.bz2 $FIREFOX_SOURCE_URL
  - mkdir -p $HOME/firefox
  - tar -jvxf /tmp/firefox.tar.bz2 -C $HOME/
  - netstat -ptln

before_script:
  - $HOME/firefox/firefox --version
  - $HOME/firefox/firefox -marionette > /dev/null 2>&1 &
  - sleep 30
  - netstat -ptln

script:
  #- go test -test.v
  - go test -test.v -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.txt -covermode=atomic -service=travis-ci